package application;

import javafx.fxml.FXML;
import javafx.scene.control.TextField;
import javafx.scene.layout.Pane;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;

public class LoginPageController{
	@FXML
	private TextField emailInput;
	@FXML
	private PasswordField passwordInput;
	@FXML
	private Label errorLabel;

	// Event Listener on Button.onAction
	@FXML
	public void userLogin(ActionEvent event){
		// TODO Autogenerated
		int m = 0;
		if(emailInput.getText() == "" || passwordInput.getText() == "" ) {
			errorLabel.setText("TextFields are empty");
			errorLabel.setVisible(true);
		}
		else {
		JdbcConnection con = new JdbcConnection();
		m = con.Login(emailInput.getText(), passwordInput.getText());
		
		if( m == 1 ) {
			application.RecipeAppMain.root.setLeft(null);
			application.RecipeAppMain.root.setRight(null);
			application.RecipeAppMain.root.setCenter(null);
			
			FxmlLoader object = new FxmlLoader();
			Pane view = object.getPage("Menu");
			application.RecipeAppMain.root.setLeft(view);
			
			view = object.getPage("Home");
			application.RecipeAppMain.root.setCenter(view);
			System.out.println("Login Successful");
		}
		else{
			errorLabel.setText("Invalid e-mail and password");
			errorLabel.setVisible(true);
			
		}
	}
	}
}
